version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dependabot-updates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      python:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "dependabot-updates"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
      timezone: "America/New_York"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      github-actions:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"
