#file: noinspection UndefinedParamsPresent
name: Deploy to Azure Function

on:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.12'
  OPENTOFU_VERSION: '1.9'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SENDER: "test@example.com"
      SMTP_SERVER: "smtp.example.com"
      SMTP_USER: "testuser"
      SMTP_PWD: "testpass"
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=test"
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v7

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v7
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install poetry-plugin-export
      run: poetry self add poetry-plugin-export

    - name: Export dependencies to requirements.txt
      run: poetry export -f requirements.txt --output requirements.txt --without-hashes

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
